const Homeproduct =
[
    {
        id: 1,
        Name: 'Nike Air Max AMD 90',
        type: 'top',
        price: '95',
        image: './img/p1.webp',
        cat: 'unisex',
    },
    {
        id: 2,
        Name: 'Nike Air Max SYSTM',
        type: 'offer',
        price: '120',
        image: './img/p2.webp',
        cat: 'man',
    },
    {
        id: 3,
        Name: 'Nike Air Max TW',
        type: 'offer',
        price: '70',
        image: './img/p3.webp',
        cat: 'man',
    },
    {
        id: 4,
        Name: 'Nike Air Max 90 Futura',
        type: 'top',
        price: '100',
        image: './img/p4.webp',
        cat: 'unisex',
    },
    {
        id: 5,
        Name: 'Nike Air Max Motif',
        type: 'new',
        price: '60',
        image: './img/p5.webp',
        cat: 'woman',
    },
    {
        id: 6,
        Name: 'Nike Air Max 90 Futura',
        type: 'top',
        price: '85',
        image: './img/p6.webp',
        cat: 'woman',
    },
    {
        id: 7,
        Name: 'Nike Air Max Bella TR 5',
        type: 'offer',
        price: '85',
        image: './img/p7.webp',
        cat: 'woman',
    },
    {
        id: 8,
        Name: 'Nike Air Max Pre-Day SE',
        type: 'new',
        price: '110',
        image: './img/p8.webp',
        cat: 'unisex',
    },
    {
        id: 9,
        Name: 'Nike Air VaporMax 2023',
        type: 'new',
        price: '110',
        image: './img/p9.webp',
        cat: 'man',
    },
    {
        id: 10,
        Name: 'Nike Air Max 90 SE',
        type: 'new',
        price: '110',
        image: './img/p10.webp',
        cat: 'unisex',
    },
    {
        id: 11,
        Name: 'Nike Air Max 90',
        type: 'new',
        price: '110',
        image: './img/p11.webp',
        cat: 'unisex',
    },
    {
        id: 12,
        Name: 'Nike Air Max TW',
        type: 'offer',
        price: '110',
        image: './img/p12.webp',
        cat: 'man',
    },
    {
        id: 13,
        Name: 'Nike Air Max AP',
        type: 'top',
        price: '110',
        image: './img/p13.webp',
        cat: 'woman',
    },
    {
        id: 14,
        Name: 'Nike Air Max Fliknit Racer',
        type: 'offer',
        price: '110',
        image: './img/p14.webp',
        cat: 'man',
    },
    {
        id: 15,
        Name: 'Nike Air Max 95',
        type: 'top',
        price: '110',
        image: './img/p15.webp',
        cat: 'man',
    },
]

export default Homeproduct;